{% set version = '1.0.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-sdtmchecks
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sdtmchecks_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sdtmchecks/sdtmchecks_{{ version }}.tar.gz
  sha256: 805282dde979095cfe160092a5342c6ec85dc3c2129ec8881d12abfd9cdff636

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    # The libstdc++.dll provided in libstdcxx v15.1.0 build h904f734_2
    # is missing `_ZSt21ios_base_library_initv`.
    # see: conda-forge/ctng-compilers-feedstock#174
    - libstdcxx !=14.3.0,!=15.1.0  # [win]
  host:
    - r-base
    - r-dplyr >=1.1.1
    - r-openxlsx
    - r-tidyselect
  run:
    - r-base
    - r-dplyr >=1.1.1
    - r-openxlsx
    - r-tidyselect
  run_constrained:
    - libstdcxx !=14.3.0,!=15.1.0           # [win]

test:
  commands:
    - $R -e "library('sdtmchecks')"           # [not win]
    - "\"%R%\" -e \"library('sdtmchecks')\""  # [win]

about:
  home: https://pharmaverse.github.io/sdtmchecks/, https://github.com/pharmaverse/sdtmchecks
  license: Apache-2.0
  summary: A series of checks to identify common issues in Study Data Tabulation Model (SDTM)
    datasets. These checks are intended to be generalizable, actionable, and meaningful
    for analysis.
  license_family: APACHE
  license_file:
    - LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r
